version: 2
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - openbsd
    ldflags:
      - -X github.com/noqqe/bump/src/bump.Version={{.Tag}}
    flags:
      - -v
archives:
  - id: bump
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - name: bump
    goarm: 6
    repository:
      owner: noqqe
      name: homebrew-tap
    download_strategy: CurlDownloadStrategy
    directory: Formula
    homepage: "https://github.com/noqqe/bump"
    description: "bump - dumb version bump"
    license: "MIT"
    test: |
      system "#{bin}/bump --version"
    install: |
      bin.install "bump"

